### ISSUE TITLE
Theme not working

### ISSUE THREAD

**Issue by ManindraDeMel** [andreasvc/vim-256noir#4]
Hi, I'm a new Vim user and i'm trying to install this new theme, its really pretty and I want to use it. However, I've done all the required steps as shown in the following screenshots with .profile, .vim/colours and .vimrc.
![Screenshot 2022-01-09 011505](https://user-images.githubusercontent.com/44416444/148647585-fadde642-70f9-468b-ab4d-01a289695b8f.png)
![Screenshot 2022-01-09 011530](https://user-images.githubusercontent.com/44416444/148647586-ada70091-0ee5-421a-a43c-0c9363d449fc.png)
![Screenshot 2022-01-09 010419](https://user-images.githubusercontent.com/44416444/148647587-7559d081-c879-4b70-a0c5-dfc996e89839.png)
 However I seem to get this error when starting up vim
![Screenshot 2022-01-09 011844](https://user-images.githubusercontent.com/44416444/148647632-2464043d-a099-4eb1-8397-a1ee04596608.png)
I then compared the 256 colourscheme to a default colourscheme and found that the codebase was completely different
![Screenshot 2022-01-09 011609](https://user-images.githubusercontent.com/44416444/148647650-cf80a751-bcbe-48fb-9fd9-574329790ae2.png)
![Screenshot 2022-01-09 011422](https://user-images.githubusercontent.com/44416444/148647652-882e3551-d58b-4066-865c-b67bae833e46.png)
Therefore, I was wondering if I was just simply installing it wrong or maybe the repo is just deprecated? Some help would be greatly appreciated 👍

**Comment by andreasvc** [comment]
It looks like you got the Github page with HTML etc, instead of the source itself. Try this link instead: https://github.com/andreasvc/vim-256noir/raw/master/colors/256_noir.vim

**Comment by ManindraDeMel** [comment]
thanks, that's my bad 👍
